/* Console shell.
 *
 * Routing is a hash and a switch rather than a router dependency: five views,
 * no nested routes, no route params. The hash keeps a view linkable and
 * survives a reload, which is all that is actually needed.
 *
 * The demo banner is not dismissable and sits above every view. A screenshot of
 * invented pest activity that is not visibly marked as invented is a claim
 * about a system that has never seen a real rat.
 */

import { useEffect, useState } from "react";
import { api } from "./api";
import { useAsync } from "./useAsync";
import { Analytics } from "./views/Analytics";
import { Cameras } from "./views/Cameras";
import { Overview } from "./views/Overview";
import { Pipeline } from "./views/Pipeline";
import { Review } from "./views/Review";
import { Runs } from "./views/Runs";

const VIEWS = [
  { id: "overview", name: "Overview" },
  { id: "review", name: "Review" },
  { id: "pipeline", name: "Cascade" },
  { id: "cameras", name: "Cameras" },
  { id: "analytics", name: "Analytics" },
  { id: "runs", name: "Runs" },
] as const;

type ViewId = (typeof VIEWS)[number]["id"];

function currentView(): ViewId {
  const hash = window.location.hash.replace("#", "");
  return (VIEWS.find((v) => v.id === hash)?.id ?? "overview") as ViewId;
}

export function App() {
  const [view, setView] = useState<ViewId>(currentView);
  const health = useAsync(() => api.health(), []);
  const overview = useAsync(() => api.overview().catch(() => null), []);

  useEffect(() => {
    const onHash = () => setView(currentView());
    window.addEventListener("hashchange", onHash);
    return () => window.removeEventListener("hashchange", onHash);
  }, []);

  const go = (id: ViewId) => {
    window.location.hash = id;
    setView(id);
  };

  const demo = health.data?.demo ?? false;
  const pending = overview.data?.counts.unverified ?? null;

  return (
    <>
      {demo ? (
        <div className="demo-banner" role="status">
          <span className="tag">Demo data</span>
          <span>Synthetic — no real footage has been collected and no model has been trained.</span>
          <span className="note">
            Every number, keyframe and trend on these screens was generated by{" "}
            <code>exv seed-demo</code>.
          </span>
        </div>
      ) : null}

      <div className="shell">
        <aside className="rail">
          <div className="rail-mark">ExpressVision</div>
          <div className="rail-sub">Operator console</div>
          <nav>
            {VIEWS.map((v) => (
              <button
                key={v.id}
                onClick={() => go(v.id)}
                aria-current={view === v.id ? "page" : undefined}
              >
                {v.name}
                {v.id === "review" && pending !== null && pending > 0 ? (
                  <span className="count">{pending.toLocaleString()}</span>
                ) : null}
              </button>
            ))}
          </nav>
          <div className="rail-foot">
            {health.data ? (
              <>
                store
                <br />
                {health.data.store}
              </>
            ) : health.error ? (
              "API unreachable"
            ) : null}
          </div>
        </aside>

        <main className="main">
          {health.data && !health.data.store_exists ? (
            <div className="view">
              <div className="callout bad">
                <p>
                  <b>No store at {health.data.store}.</b>
                </p>
                <p>
                  Collect some events with <code>exv run data/fixture.mp4</code>, or build a
                  labelled demo store with <code>exv seed-demo</code> and serve it with{" "}
                  <code>exv serve --db out/demo.db --media-root out/demo</code>.
                </p>
              </div>
            </div>
          ) : (
            <>
              {view === "overview" ? <Overview /> : null}
              {view === "review" ? <Review onVerdict={overview.reload} /> : null}
              {view === "pipeline" ? <Pipeline /> : null}
              {view === "cameras" ? <Cameras /> : null}
              {view === "analytics" ? <Analytics /> : null}
              {view === "runs" ? <Runs /> : null}
            </>
          )}
        </main>
      </div>
    </>
  );
}
